### ISSUE TITLE
AttributeError: <class 'qiime2.core.type.grammar.UnionExp'> object has no attribute 'predicate'

### ISSUE THREAD

**Issue by maque4004** [biocore/mmvec#116]
Hi Jamie,
I installed mmvec via conda,  it showed successful installation.
Then I run the command: qiime mmvec --help,
but raised an error:
AttributeError: <class 'qiime2.core.type.grammar.UnionExp'> object has no attribute 'predicate'

My qiime2 version is 2019.4

Any suggestion?
Thank you in advance!

Best,
Yichen

**Comment by mortonjt** [comment]
I haven't seen that error before. Have you tried the latest version of
qiime? The installation is known to work with 2019.7 and 2019.10

**Comment by maque4004** [comment]
Thanks, Jamie!
No problem with version 2019.10.

Three more questions:
1. I ran qiime mmvec paired-omics command, got conditianals.qza, and unzip it, then got the csv file.
In this file,  largest values stand for the highest co-occurrence probabilities, how about the negtive values? Do they mean there are no co-occurrence between the micobe and metabolite, or even exclusive?
2. In the biplot,  --p-number-of-features: the number of most important features. How can I say some certain features are the most top important ones?  Are they the most correlated with some metabolites?
3. In qiime2 emperor view, the sequences for each arrow was showed, can I hide them?
![image](https://user-images.githubusercontent.com/45165322/71639221-f2a3b200-2cad-11ea-80e3-85a09a14a4ab.png)

Looking forward to your reply~ Thank you for your patience~

Best,
Yichen

**Comment by mortonjt** [comment]
Glad to hear that qiime2-2019.10 works!

Regarding the questions

1. These are log-transformed conditional probabilities, that are centered around the mean probability.  When I mean centered, I mean that the a zero score refers to the average conditional probability.  Negative values just mean that there is a low probability of the microbe/metabolite co-occurring (and that it is lower than average).  Positive values indicate that there is a high probability of the microbe/metabolite co-occurring (higher than average).
2. --p-number-of-features grabs the microbes that have the longest arrows.  The length of the arrow refers to the magnitude - you can think of it as the variance in the metabolites explained by the microbes.  So the longer the arrow, the more of the metabolite variance is described by that specific microbe
3. Yup, it is in the top right gear - you can toggle label visibility

**Comment by maque4004** [comment]
Thanks, Jamie, very clear.

I checked the input microbial OTU table in cf example, it's a raw table. So we don't need to rarefy or normalize the table before run mmvec?

**Comment by mortonjt** [comment]
No need to rarefy - mmvec was engineered to handled different sequencing depths.

**Comment by maque4004** [comment]
Hi Jamie,

Thank you for reply!

1. the third point above--visualize biplot in emperor, as you suggested, if I set visibility, the arrow would be hiden with sequence together, I was wondering if I could only hide the sequences, but keep the arrow. 
 
2. I repeated the standalone mmvec in the tutorial:
mmvec paired-omics --microbe-file otus_nt.biom --metabolite-file lcms_nt.biom --summary-dir summary
tensorboard --logdir .

But the curve seems strange:
![image](https://user-images.githubusercontent.com/45165322/71723748-cc764180-2e68-11ea-841f-d0a9c557fde5.png)

3. I didn't know the default parameter values of the standalone script: mmvec paired-omics --help, can I think they are same with the qiime2 mmvec paired-omics?
Like,  --min-feature-count INTEGER, I can't tell the default value from the help docs, but in qiime2, it said to be 10.

Thank you again for your help.


Best,
Yichen

**Comment by mortonjt** [comment]
1. Yes, that is in the gear icon.  See 
![image](https://user-images.githubusercontent.com/4184797/71732911-5fd25700-2e16-11ea-87ad-c186560477d0.png)

2. You may have to tinker with the `--epochs` option - I'd set that to 1000 epochs (i.e. 1000 full iteractions over the dataset). If you are still not getting a good readout, try setting `summary-interval=1` to write summaries every second.  There is a detailed writeup on this in the FAQs -- definitely feel free to add in edits if this is not clear.

3. Most of the defaults are the same (with the exception of `summary_interval`).  The defaults for the standalone script can be found here: https://github.com/biocore/mmvec/blob/master/scripts/mmvec
Probably will be a good idea to make this available through the CLI in the future.

**Comment by maque4004** [comment]
Thank you so much!

**Comment by mortonjt** [comment]
@maque4004 glad to help! I'm going to close this issue now since it looks resolved.  Feel free to reopen.

**Comment by maque4004** [comment]
Hi Jamie, 
my codes are(I got 80 samples in total):
mmvec paired-omics --microbe-file otu-table-raw.biom --metabolite-file metabolites-table.biom --num-testing-examples 20 --epochs 1000 --summary-interval 1 --summary-dir mmvec-standalone-summary-test20-epoch1000-intv1 
tensorboard --logdir .


![image](https://user-images.githubusercontent.com/45165322/71777462-44647900-2fdb-11ea-97b4-be937b267d57.png)
Does the curve look good enough? If not, how can I optimize the parameters?

P.S. I run the command in your tutorial, but the curves were not good as you presented.
![image](https://user-images.githubusercontent.com/45165322/71777614-49c2c300-2fdd-11ea-96b3-8765871a1a9a.png)
mmvec paired-omics --microbe-file otus_nt.biom --metabolite-file lcms_nt.biom --epochs 1000 --summary-interval 1 --summary-dir summary

**Comment by mortonjt** [comment]
The first set of commands looks reasonable - so I'd stick with those.

**Comment by maque4004** [comment]
Sorry, the first set of commands was my data;
but the second set of commands was not my data, it was the cf example data in your tutorials, for the second picture of curves, I meant I couldn't get the same results as good as you presented in the tutorials.
If the curves do not reach a plateau,like the second picture, then results are not reliable? 
How can I optimize the parameters to get nice curves?
Thank you!

**Comment by mortonjt** [comment]
yes, it means that the results are suboptimal and that you should try to
bump up the epochs.
The commands provided in the tutorial were done with a smaller number of
epochs (for the sake of demonstration).
The standard run is expected to take hours to days depending on the size of
the dataset.
